CREATE TABLE card (
  id VARCHAR(36) PRIMARY KEY NOT NULL,
  codename VARCHAR NOT NULL UNIQUE,
  title VARCHAR NOT NULL,
  description VARCHAR NOT NULL,
  priority INTEGER NOT NULL,
  column VARCHAR(36) NOT NULL,
  FOREIGN KEY (column) REFERENCES column(id) 
);